---
# Master playbook for setting up KVM guests on a KVM host using an inventory
# Requires a KVM host and qemu-img, virsh, virt-customize and virt-sysprep.
#
# Limit your inventory to the group of VMs you want to set up, like this:
# ansible-playbook \
# --ask-become-pass \
# --limit kvmhost,guests \
# --inventory ./inventory/hosts.yml \
# ./virt-infra.yml
#
- hosts: kvmhost
  gather_facts: no
  tasks:
    - name: create libvirt image path
      file:
        path: /var/lib/libvirt/images
        state: directory
    - name: download images
      get_url:
        url: "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2"
        dest: "/var/lib/libvirt/images"
- hosts: all
  gather_facts: no
  roles:
    - ansible-role-virt-infra

# Now you can use the inventory to do anything else you want...
