---
lab:
  hosts:
    node[1:2]:
    controller:
  vars:
      virt_infra_user: ansible
      virt_infra_state: running
      virt_infra_variant: centos7.0
      virt_infra_distro_image: centos8.qcow2
      virt_infra_distro_image_url: http://download.goffinet.org/kvm/centos8.qcow2
      virt_infra_distro_image_checksum_url: http://download.goffinet.org/kvm/centos8.qcow2.sha256sum
      ansible_python_interpreter: /usr/libexec/platform-python
      virt_infra_disk_cmd:
        - echo 'fastestmirror=1' >> /etc/dnf/dnf.conf
